~VERSION INFORMATION
 VERS .                              2.0 : LAS VERSION 2.0 BY MEGAEDIT v2.77
 WRAP .                               No : One line per depth
~WELL INFORMATION
 STRT .M                       4002.0000 : Start Depth/Time
 STOP .M                       4029.9200 : Stop Depth/Time
 STEP .M                          0.0025 : Step Data
 NULL .                          -999.25 : NULL
 WELL .                                5 : Well Name
 FLD  .                          Анисово : Field Name
 LOC  .                                  : Location
 SRVC .      AO MNGF TUMENPROMGEOPHISIKA : SRVC
 DATE .                         20.01.03 : Date of Loggin
~CURVE INFORMATION SECTION
 DEPT .M                                 : 1
 SPDM .                                  : 2  Синонимов 9
 BMK1 .                                  : 3  Синонимов 9
 BMK2 .                                  : 4  Синонимов 9
 BMK3 .                                  : 5  Синонимов 9
 BMK4 .                                  : 6  Синонимов 9
 BMK5 .                                  : 7  Синонимов 9
 BMK6 .                                  : 8  Синонимов 9
 UEKR .                                  : 9  Синонимов 9
 RAD1 .                                  : 10 Синонимов 9
 RAD2 .                                  : 11 Синонимов 9
 RAD3 .                                  : 12 Синонимов 9
 RAD4 .                                  : 13 Синонимов 9
 RAD5 .                                  : 14 Синонимов 9
 RAD6 .                                  : 15 Синонимов 9
 DEVI .                                  : 16 Синонимов 9
 AZIM .                                  : 17 Синонимов 9
 AZ1B .                                  : 18 Синонимов 9
 TEMP .DEGF                              : 19 Temerature
 AZ   .                                  : 20 Синонимов 9
 AY   .                                  : 21 Синонимов 9
 AX   .                                  : 22 Синонимов 9
 TZ   .                                  : 23 Синонимов 9
 TY   .                                  : 24 Синонимов 9
 TX   .                                  : 25 Синонимов 9
 RADS .                                  : 26 Middle radius
~PARAMETR INFORMATION SECTION
 NP6  .                                0 : Correction not present
~OTHER INFORMATION
#       DEPT        SPDM        BMK1        BMK2        BMK3        BMK4        BMK5        BMK6        UEKR        RAD1        RAD2        RAD3        RAD4        RAD5        RAD6        DEVI        AZIM        AZ1B        TEMP          AZ          AY          AX          TZ          TY          TX        RADS
~ASCII DATA
