/* LabWindows User Interface Resource (UIR) Include File                  */
/* Copyright (c) National Instruments 1992. All Rights Reserved.          */

/* WARNING: Do not add to, delete from, or otherwise modify the contents  */
/*          of this include file.                                         */


#define  LOADING  0
#define  LOADING_BOX  0
#define  LOADING_PLX_NUMBER  1
#define  LOADING_PLX_LIST  2
#define  LOADING_SERIAL_NUMBER  3
#define  LOADING_DSP_TYPE  4
#define  LOADING_QUARTZ  5
#define  LOADING_TEXT  6
#define  LOADING_REVISION  7
#define  LOADING_DAC  8
#define  LOADING_ACCESS  9
#define  LOADING_STATUS  10
#define  LOADING_BIOS_LOADING  11
#define  LOADING_DOS_EXIT  12
