/* LabWindows User Interface Resource (UIR) Include File                  */
/* Copyright (c) National Instruments 1992. All Rights Reserved.          */

/* WARNING: Do not add to, delete from, or otherwise modify the contents  */
/*          of this include file.                                         */


#define  SYNCHRO  0
#define  SYNCHRO_GRAPH  0
#define  SYNCHRO_BOX1  1
#define  SYNCHRO_START1  2
#define  SYNCHRO_LOOP1  3
#define  SYNCHRO_START_ALL  4
#define  SYNCHRO_LOOP_ALL  5
#define  SYNCHRO_DONE  6
#define  SYNCHRO_ZOOMX  7
#define  SYNCHRO_ZOOM  8
#define  SYNCHRO_MIN  9
#define  SYNCHRO_MAX  10
#define  SYNCHRO_ADC_CHANNEL  11
#define  SYNCHRO_AMPLIFICATION_1  12
#define  SYNCHRO_AMPLIFICATION_2  13
#define  SYNCHRO_MILLI_VOLT  14
#define  SYNCHRO_SYNCHRO  15

#define  ANALOGPARS  1
#define  ANALOGPARS_TEXTBOX  0
#define  ANALOGPARS_TYPE  1
#define  ANALOGPARS_MODE_1  2
#define  ANALOGPARS_MODE_2  3
#define  ANALOGPARS_CHANNEL  4
#define  ANALOGPARS_POROG_TEXT_1  5
#define  ANALOGPARS_POROG  6
#define  ANALOGPARS_EXIT  7
#define  ANALOGPARS_CANCEL  8
#define  ANALOGPARS_POROG_TEXT_2  9
