{ значения адресов управляющих регистров 										}
.const  	Sys_Ctrl_Reg					=	0x3FFF;
.const  	Dm_Wait_Reg						=	0x3FFE;
.const  	Tperiod_Reg						=	0x3FFD;
.const  	Tcount_Reg						=	0x3FFC;
.const  	Tscale_Reg						=	0x3FFB;
.const  	Sport1_Ctrl_Reg				= 	0x3FF2;
.const  	Sport1_Sclkdiv					= 	0x3FF1;
.const  	Sport1_Rfsdiv					=	0x3FF0;
.const  	Sport1_Autobuf_Ctrl			= 	0x3FEF;
.const  	Sport0_Ctrl_Reg				= 	0x3FF6;
.const  	Sport0_Sclkdiv					= 	0x3FF5;
.const  	Sport0_Rfsdiv					=	0x3FF4;
.const  	Sport0_Autobuf_Ctrl			=	0x3FF3;
.const 	Prog_Flag_Comp_Sel_Ctrl    =	0x3FE6;
.const 	Prog_Flag_Data             =	0x3FE5;
.const 	BDMA_Word_Count            =	0x3FE4;
.const 	BDMA_Control               =	0x3FE3;
.const 	BDMA_External_Address      =	0x3FE2;
.const 	BDMA_Internal_Address      =	0x3FE1;

{ регистры со стороны DSP															}
.const TTL_IN								=	0x000;
.const TTL_OUT								=	0x200;
.const READ_ADC							=	0x001;
.const SET_ADC_CHANNEL					=	0x201;


