/* LabWindows User Interface Resource (UIR) Include File                  */
/* Copyright (c) National Instruments 1992. All Rights Reserved.          */

/* WARNING: Do not add to, delete from, or otherwise modify the contents  */
/*          of this include file.                                         */


#define  DAC  0
#define  DAC_BOX  0
#define  DAC_BOX1  1
#define  DAC_BOX2  2
#define  DAC_TEXTBOX  3
#define  DAC_PLATA_LED  4
#define  DAC_OUTPUT_MODE  5
#define  DAC_IRQ  6
#define  DAC_SIGNAL_TYPE  7
#define  DAC_TEXT_LAB1  8
#define  DAC_DAC_RATE  9
#define  DAC_TEXT_LAB2  10
#define  DAC_FREQUENCY  11
#define  DAC_F_LARGE_MINUS_STEP  12
#define  DAC_F_SMALL_MINUS_STEP  13
#define  DAC_F_SMALL_PLUS_STEP  14
#define  DAC_F_LARGE_PLUS_STEP  15
#define  DAC_TEXT_LAB3  16
#define  DAC_AMPLITUDE  17
#define  DAC_A_LARGE_MINUS_STEP  18
#define  DAC_A_SMALL_MINUS_STEP  19
#define  DAC_A_SMALL_PLUS_STEP  20
#define  DAC_A_LARGE_PLUS_STEP  21
#define  DAC_START_STOP  22
#define  DAC_DONE  23
