/* LabWindows User Interface Resource (UIR) Include File                  */
/* Copyright (c) National Instruments 1992. All Rights Reserved.          */

/* WARNING: Do not add to, delete from, or otherwise modify the contents  */
/*          of this include file.                                         */


#define  MENUBAR  0
#define  MENUBAR_ADC  0
#define  MENUBAR_DAC  256
#define  MENUBAR_TTL  512
#define  MENUBAR_QUIT  768

#define  INPUT  0
#define  INPUT_AUTOSCALE  0
#define  INPUT_GRID  1
#define  INPUT_CHANNELS  2
#define  INPUT_START  3
#define  INPUT_GRAPH1  4
#define  INPUT_GRAPH2  5
#define  INPUT_GRAPH3  6
#define  INPUT_GRAPH4  7
#define  INPUT_BOX1  8

#define  DISK  1
#define  DISK_BOX  0
#define  DISK_DRAWMODE  1
#define  DISK_CHANNEL  2
#define  DISK_IRQ_NUMBER  3
#define  DISK_COUNT  4
#define  DISK_DRAW  5
#define  DISK_START  6
#define  DISK_GRAPH  7
#define  DISK_BOX1  8

#define  ADCPARAM  2
#define  ADCPARAM_BOX1  0
#define  ADCPARAM_TEXT1  1
#define  ADCPARAM_ADC_RATE  2
#define  ADCPARAM_ADC_RATE1  3
#define  ADCPARAM_TEXT5  4
#define  ADCPARAM_TEXT6  5
#define  ADCPARAM_INTER_KADR_DELAY  6
#define  ADCPARAM_TEXT2  7
#define  ADCPARAM_TEXT7  8
#define  ADCPARAM_CANAL_RATE  9
#define  ADCPARAM_BOX2  10
#define  ADCPARAM_AMPLIFICATION_1  11
#define  ADCPARAM_AMPLIFICATION_2  12
#define  ADCPARAM_TEXT3  13
#define  ADCPARAM_TEXT4  14
#define  ADCPARAM_MILLI_VOLT  15
#define  ADCPARAM_ACCESS  16
#define  ADCPARAM_TEXT8  17
#define  ADCPARAM_DISPLAY  18
#define  ADCPARAM_DISK  19

#define  DACPARAM  3
#define  DACPARAM_TEXT1  0
#define  DACPARAM_DAC_RATE  1
#define  DACPARAM_DAC_NUMBER  2
#define  DACPARAM_TEXTBOX  3
#define  DACPARAM_SIGNAL_TYPE  4
#define  DACPARAM_TEXT2  5
#define  DACPARAM_AMPLITUDE  6
#define  DACPARAM_TEXT3  7
#define  DACPARAM_FREQUENCY  8
#define  DACPARAM_START  9
#define  DACPARAM_BOX  10

#define  TTL  4
#define  TTL_BOX1  0
#define  TTL_INPUTS  1
#define  TTL_INPUT1  2
#define  TTL_INPUT2  3
#define  TTL_INPUT3  4
#define  TTL_INPUT4  5
#define  TTL_INPUT5  6
#define  TTL_INPUT6  7
#define  TTL_INPUT7  8
#define  TTL_INPUT8  9
#define  TTL_INPUT9  10
#define  TTL_INPUT10  11
#define  TTL_INPUT11  12
#define  TTL_INPUT12  13
#define  TTL_INPUT13  14
#define  TTL_INPUT14  15
#define  TTL_INPUT15  16
#define  TTL_INPUT16  17
#define  TTL_BOX2  18
#define  TTL_OUTPUTS  19
#define  TTL_OUTPUT1  20
#define  TTL_OUTPUT2  21
#define  TTL_OUTPUT3  22
#define  TTL_OUTPUT4  23
#define  TTL_OUTPUT5  24
#define  TTL_OUTPUT6  25
#define  TTL_OUTPUT7  26
#define  TTL_OUTPUT8  27
#define  TTL_OUTPUT9  28
#define  TTL_OUTPUT10  29
#define  TTL_OUTPUT11  30
#define  TTL_OUTPUT12  31
#define  TTL_OUTPUT13  32
#define  TTL_OUTPUT14  33
#define  TTL_OUTPUT15  34
#define  TTL_OUTPUT16  35
#define  TTL_BOX3  36
#define  TTL_TEXT3  37
#define  TTL_ZERO  38
#define  TTL_ONE  39
#define  TTL_RUNNING_ZERO  40
#define  TTL_RUNNING_ONE  41
#define  TTL_BOX4  42
