// Working with L-1250 L-1251 L-305 L-264


// Commands supported ADSP  on 1250/1 boards
#define  cmSTOP_1251               0
#define  cmADC_CHAN_1251           1
#define  cmOUT_DAC_1251            2
#define  cmSTREAM_1251             3
#define  cmSOFT_1251               4
#define  cmSAMPLE_1251             5
#define  cmTTL_IN_1251             6
#define  cmTTL_OUT_1251            7
#define  cmIRQ_SIMPLE_1251         8
#define  cmIRQ_ADC_CHAN_1251       9
#define  cmIRQ_KADR_1251           10

#define  cmCALIBR_1251             11

#define  cmTEST_1251               12
#define  cmDAC_STREAM_1251         13
#define  cmMEMORY_STATE_1251       14

#define  cmFILTER_1251             15
#define  cmFLT_NO_LOAD_1251        16
#define  cmSET_MULTI_1251          17
#define  cmSET_SCALE_1251          18

#define  cmSET_UVX_1251            19
#define  cmSET_DSP_SPEED_1251      20
#define  cmSET_WAITSTATE_1251      21
#define  cmSET_DELAY_1251          22
#define  cmSYNCHRO_MODE_1251       23
#define  cmDAC_CONFIG_1251         24
#define  cmFIFO_CONFIG_1251        25
#define  cmSOFT_MEMORY_1251        26

#define  cmPROGRAM_1251            28
#define  cmWRITE_TO_MEM_1251       29
#define  cmREAD_FROM_MEM_1251      30
#define  cmGET_LSM_NAME_1251       31
#define  cmSET_2FIFO_TYPE_1251     32
#define  cmSET_LM_DAC_1251         33
#define  cmGET_LM_TTL_1251         34
#define  cmCOMPARATPR_1251         35
#define  cmTEST_PM_1251            36
#define  cmLOW_POWER_1251          37
#define  cmLM404_1251              39

// defines for Set/Get Parameters

#define L1251_MEM_STATE       1
#define L1251_MEM_PM_STATE    2
