/* LabWindows User Interface Resource (UIR) Include File                  */
/* Copyright (c) National Instruments 1992. All Rights Reserved.          */

/* WARNING: Do not add to, delete from, or otherwise modify the contents  */
/*          of this include file.                                         */


#define  PLATA  0
#define  PLATA_BOX  0
#define  PLATA_BOX1  1
#define  PLATA_BOX2  2
#define  PLATA_BOX3  3
#define  PLATA_BOX4  4
#define  PLATA_BOX6  5
#define  PLATA_BOX5  6
#define  PLATA_BOARD  7
#define  PLATA_DSP_TYPE  8
#define  PLATA_SERIAL_NUMBER  9
#define  PLATA_DAC  10
#define  PLATA_QUARTZ  11
#define  PLATA_TEXT  12
#define  PLATA_REVISION  13
#define  PLATA_ACCESS  14
#define  PLATA_INTERRUPT  15
#define  PLATA_ACTIVE_CHANNELS  16
#define  PLATA_FIRST  17
#define  PLATA_SECOND  18
#define  PLATA_THIRD  19
#define  PLATA_FORTH  20
#define  PLATA_FIFTH  21
#define  PLATA_SIXTH  22
#define  PLATA_SEVENTH  23
#define  PLATA_EIGTH  24
#define  PLATA_TEXT1  25
#define  PLATA_CHANNEL_QUANTITY  26
#define  PLATA_TIME  27
#define  PLATA_TEXT2  28
#define  PLATA_POINTS_QUANTITY  29
#define  PLATA_TEXT3  30
#define  PLATA_ADC_RATE  31
#define  PLATA_INTER_KADR_DELAY  32
#define  PLATA_CANAL_RATE  33
#define  PLATA_TEXT4  34
#define  PLATA_FIFO_ADDRESS  35
#define  PLATA_FIFO_LENGTH  36
#define  PLATA_AMPLIFICATION  37
#define  PLATA_MILLI_VOLT  38
#define  PLATA_FILENAME  39
#define  PLATA_SBOR  40
#define  PLATA_STATUS  41
#define  PLATA_EXIT  42
#define  PLATA_PROGRESS_INDICATOR  43
#define  PLATA_TEXT10  44
#define  PLATA_TEXT11  45
